
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-14
owner: ucsb-cs156-s25
repo_name: team01-s25-14
pull_requests: [{"author":{"id":"U_kgDOCM7wqA","is_bot":false,"login":"siddhimundhra1","name":""},"headRefName":"siddhimundhra1-helprequest-get-by-id","number":67,"title":"Siddhimundhra1 helprequest get by","url":"https://github.com/ucsb-cs156-s25/team01-s25-14/pull/67"}]
