
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-14
owner: ucsb-cs156-s25
repo_name: team01-s25-14
pull_requests: [{"author":{"id":"U_kgDOB09Zlw","is_bot":false,"login":"ryanchoi07","name":""},"headRefName":"ryanchoi07-UCSBDiningCommonsMenuItem-create-db","number":48,"title":"rchoi - create database table for UCSBDiningCommonsMenuItem (#8)","url":"https://github.com/ucsb-cs156-s25/team01-s25-14/pull/48"},{"author":{"id":"U_kgDOB3D-ww","is_bot":false,"login":"chloeandersen-ucsb","name":""},"headRefName":"Chloe-RecReq-23","number":46,"title":"Adding PUT endpoint for a single record in RecommendationRequest table","url":"https://github.com/ucsb-cs156-s25/team01-s25-14/pull/46"},{"author":{"id":"U_kgDOB3D-ww","is_bot":false,"login":"chloeandersen-ucsb","name":""},"headRefName":"Chloe-RecReq-22","number":45,"title":"Chloe: Add GET (show) endpoint for a single record in RecommendationRequest","url":"https://github.com/ucsb-cs156-s25/team01-s25-14/pull/45"}]
