
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-14
owner: ucsb-cs156-s25
repo_name: team01-s25-14
pull_requests: [{"author":{"id":"U_kgDOB09Zlw","is_bot":false,"login":"ryanchoi07","name":""},"headRefName":"rc-put-for-menuitems-table","number":64,"title":"Rc put for menuitems table","url":"https://github.com/ucsb-cs156-s25/team01-s25-14/pull/64"},{"author":{"id":"U_kgDOB09Zlw","is_bot":false,"login":"ryanchoi07","name":""},"headRefName":"rc-menuitems-get-by-id","number":63,"title":"implement controller get by id for ucsbdiningcommonsmenuitems","url":"https://github.com/ucsb-cs156-s25/team01-s25-14/pull/63"},{"author":{"id":"U_kgDOB09Zlw","is_bot":false,"login":"ryanchoi07","name":""},"headRefName":"ryanchoi07-UCSBDiningCommonsMenuItem-create-db","number":62,"title":"rc - test coverage for UCSBDiningCommonsMenuItem and make controller …","url":"https://github.com/ucsb-cs156-s25/team01-s25-14/pull/62"}]
