
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-14
owner: ucsb-cs156-s25
repo_name: team01-s25-14
pull_requests: [{"author":{"id":"MDQ6VXNlcjY1NDY4MjU1","is_bot":false,"login":"karenlyuan","name":"Karen Yuan"},"headRefName":"karenlyuan-articles-get-endpoint","number":54,"title":"ky - add GET by id for articles","url":"https://github.com/ucsb-cs156-s25/team01-s25-14/pull/54"},{"author":{"id":"MDQ6VXNlcjY1NDY4MjU1","is_bot":false,"login":"karenlyuan","name":"Karen Yuan"},"headRefName":"karenlyuan-Articles-create-controller","number":53,"title":"ky - create articles controller, add GET /all and POST methods","url":"https://github.com/ucsb-cs156-s25/team01-s25-14/pull/53"},{"author":{"id":"U_kgDOB3Ewuw","is_bot":false,"login":"shruthiunnithan","name":"Shruthi Santhosh Unnithan"},"headRefName":"shruthiunnithan-MenuItemReview-create-db","number":52,"title":"Creating Controller and setting up GET and POST","url":"https://github.com/ucsb-cs156-s25/team01-s25-14/pull/52"},{"author":{"id":"MDQ6VXNlcjY1NDY4MjU1","is_bot":false,"login":"karenlyuan","name":"Karen Yuan"},"headRefName":"Karen-ArticlesTable","number":51,"title":"Created database table for Articles called \"articles\"","url":"https://github.com/ucsb-cs156-s25/team01-s25-14/pull/51"}]
